# Generated by Django 3.1 on 2020-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_flg',
            field=models.BooleanField(default=False),
        ),
    ]
